function retry_failed_task(task_key)
task = get_redis_hash(task_key);
if ~strcmpi(task.status, 'failed')
    return
end
mrc.redis_cmd({'MULTI', ...
    ['LREM failed_tasks 0 ' task_key], ...
    ['LPUSH pending_tasks ' task_key ], ...
    ['HMSET ' task_key ' status pending'], ...
    'EXEC'});
end

